const descriptions = [
    "A stunning campground surrounded by nature.",
    "Perfect for outdoor enthusiasts.",
    "Escape to tranquility.",
    "Experience the beauty of the outdoors.",
    "Unplug and unwind in nature.",
    "Discover the magic of the wilderness.",
    "Savor the serenity of your surroundings.",
    "Immerse yourself in the wonders of nature.",
    "Breathe in the fresh mountain air.",
    "Listen to the soothing sounds of the forest.",
    "Embrace the calmness of a lakeside retreat.",
    "Indulge in the peaceful ambiance of the countryside.",
    "Feel the warmth of a campfire under the starry sky.",
    "Connect with nature in this secluded haven.",
    "Roam freely in a meadow of wildflowers.",
    "Camp by a crystal-clear stream.",
    "Marvel at the beauty of a cascading waterfall.",
    "Surrender to the charm of a moonlit night.",
    "Escape the hustle and bustle for a peaceful escape.",
    "Relax in the shade of towering pine trees.",
    "Find joy in the simplicity of rustic living.",
    "Discover the secrets of a hidden oasis.",
    "Revel in the magic of a starlit sanctuary.",
    "Embark on a journey to a golden glade.",
    "Explore the wonders of an enchanted valley.",
    "Experience the thrill of riverside camping.",
    "Unwind in the embrace of a forest retreat.",
    "Feel the serenity of a lakeside paradise.",
    "Camp in the heart of a wildlife wonderland.",
    "Savor the solitude of a remote campsite.",
    "Reconnect with nature in a pristine meadow.",
    "Marvel at the beauty of a sunset summit.",
    "Discover the allure of a misty mountain retreat.",
    "Escape to a tranquil timberland.",
    "Camp in the midst of an alpine aura.",
    "Feel the energy of a bustling campfire.",
    "Immerse yourself in the charm of a quaint quarters.",
    "Experience the luxury of lakeside living.",
    "Marvel at the colors of a vibrant vista.",
    "Camp in the shade of a canopy cove.",
    "Revel in the beauty of a glowing glade.",
    "Embrace the whimsy of a woodland wonder.",
    "Discover the treasures of twilight tranquility.",
    "Camp by the serene shores of a lily pad lodge.",
    "Escape to a meadow where fireflies dance.",
    "Feel the eternal echo of the wilderness.",
    "Roam freely in a gentle grove.",
    "Discover the charm of a dewdrop dell.",
    "Listen to the tranquil tides of a wandering willow.",
    "Camp in luxury by a lakeside oasis.",
    "Marvel at the misty mountainside.",
    "Feel the serenity of a secluded valley.",
    "Discover the secrets of a lunar lagoon.",
    "Savor the thrill of camping by a cascading falls.",
    "Embrace the magic of a sunrise serenity.",
    "Revel in the beauty of a moonlit meadow.",
    "Camp on the edge of breathtaking bluffs.",
    "Discover the tranquility of a ponderosa paradise.",
    "Surrender to the allure of emerald echoes.",
    "Roam freely in a woodland whispers.",
    "Camp by a crystal-clear campsite.",
    "Experience the wholesomeness of wilderness.",
    "Feel the refuge of a rocky ridge.",
    "Discover peace in the shade of silver springs.",
    "Revel in the dreaminess of daisy dell.",
    "Explore a rocky retreat by a mountain stream.",
    "Indulge in the luxury of a vista view.",
    "Savor the beauty of a crystal cove.",
    "Discover the excitement of rolling rapids.",
    "Camp under the shade of birch bliss.",
    "Experience the serenity of a sunflower sanctuary.",
    "Embark on an epic escapade in the great outdoors.",
    "Revel in the grandeur of a grand grotto.",
    "Discover the wonders of wildlife whimsy.",
    "Savor the treasures of twilight tranquility.",
    "Experience the enchantment of forest fantasy.",
    "Reconnect with nature in an alpine aura.",
    "Camp under the starlit shores.",
    "Find solace in a cozy corner by the campfire.",
    "Revel in the charm of a grizzly grove.",
    "Discover the beauty of shady shores.",
    "Unwind in a tranquil timberland.",
    "Roam freely in a glistening glen.",
    "Experience the beauty of sapphire springs.",
    "Camp under the sunflower summit.",
    "Revel in the blissful bluff overlooking the landscape.",
    "Discover the magic of a canopy cove.",
    "Savor the glimmering glade of the forest.",
    "Embrace the whimsical waters of a campsite.",
    "Explore the foggy foothills for a unique camping experience.",
    "Indulge in the beauty of piney peaks.",
    "Reconnect with nature in a daisy dell.",
    "Camp in a rocky retreat surrounded by nature.",
    "Experience the charm of maple meadows.",
    "Discover the allure of a crimson cove.",
    "Revel in the tranquility of hush haven.",
    "Savor the beauty of a lavender lodge.",
    "Indulge in the charm of twinkling trails.",
    "Discover the wonders of wild whisper.",
    "Revel in fireside fables by the campfire.",
    "Experience the beauty of azure acres.",
    "Embark on a journey to Eagle's Eyrie.",
    "Discover the lush lagoon of a hidden grove.",
    "Revel in the glowing grove of the moonlight.",
    "Savor the serenity of a redwood refuge.",
    "Indulge in the calmness of a quiet cove.",
    "Reconnect with nature in a majestic meadow.",
    "Roam freely in a rustic ridge.",
    "Discover the secrets of a hidden hollow.",
    "Experience the allure of a sapphire sanctuary.",
    "Camp under the stars in a lunar lodge.",
    "Revel in the serenity of a sapphire serenity.",
    "Discover the gentleness of a gentle gaze.",
    "Experience the magic of a rustic rendezvous.",
    "Savor the shimmering shores of a campsite.",
    "Explore the whimsy of a woodland wonder.",
    "Indulge in the dreamy atmosphere of a dell.",
    "Discover the bountiful bluff overlooking the landscape.",
    "Reconnect with nature in a wilderness wonderland.",
    "Roam freely in a twilight timberland.",
    "Experience the mysteries of a mystical meadow.",
    "Camp under the stars in a sunset shelter.",
    "Revel in the heights of a haven heights.",
    "Discover the wonders of Eagle's Enclave.",
    "Roam freely in nature's nook.",
    "Camp by the crimson campsite.",
    "Experience the mystic mesa under the moonlight.",
    "Discover the radiance of a rustic retreat.",
    "Revel in the tranquility of tranquil timbers.",
    "Savor the luxury of a lily pad lodge.",
    "Indulge in a moonlit mingle by a lakeside oasis."
];
module.exports = descriptions;