const cityStatePairs = [
    { city: 'New York', state: 'NY' },
    { city: 'Los Angeles', state: 'CA' },
    { city: 'Chicago', state: 'IL' },
    { city: 'Houston', state: 'TX' },
    { city: 'Phoenix', state: 'AZ' },
    { city: 'Philadelphia', state: 'PA' },
    { city: 'San Antonio', state: 'TX' },
    { city: 'San Diego', state: 'CA' },
    { city: 'Dallas', state: 'TX' },
    { city: 'San Jose', state: 'CA' },
    { city: 'Austin', state: 'TX' },
    { city: 'Seattle', state: 'WA' },
    { city: 'Denver', state: 'CO' },
    { city: 'Miami', state: 'FL' },
    { city: 'Atlanta', state: 'GA' },
    { city: 'Boston', state: 'MA' },
    { city: 'San Francisco', state: 'CA' },
    { city: 'Detroit', state: 'MI' },
    { city: 'Washington', state: 'DC' },
    { city: 'Nashville', state: 'TN' },
    { city: 'Las Vegas', state: 'NV' },
    { city: 'Charlotte', state: 'NC' },
    { city: 'Portland', state: 'OR' },
    { city: 'Raleigh', state: 'NC' },
    { city: 'Minneapolis', state: 'MN' },
    { city: 'Cleveland', state: 'OH' },
    { city: 'Columbus', state: 'OH' },
    { city: 'Indianapolis', state: 'IN' },
    { city: 'Pittsburgh', state: 'PA' },
    { city: 'Kansas City', state: 'MO' },
    { city: 'Orlando', state: 'FL' },
    { city: 'Salt Lake City', state: 'UT' },
    { city: 'Tampa', state: 'FL' },
    { city: 'St. Louis', state: 'MO' },
    { city: 'Baltimore', state: 'MD' },
    { city: 'Denver', state: 'CO' },
    { city: 'San Diego', state: 'CA' },
    { city: 'Oakland', state: 'CA' },
    { city: 'New Orleans', state: 'LA' },
    { city: 'Milwaukee', state: 'WI' },
    { city: 'Memphis', state: 'TN' },
    { city: 'Buffalo', state: 'NY' },
    { city: 'Louisville', state: 'KY' },
    { city: 'St. Paul', state: 'MN' },
    { city: 'Anchorage', state: 'AK' },
    { city: 'Honolulu', state: 'HI' },
    { city: 'Albuquerque', state: 'NM' },
    { city: 'Omaha', state: 'NE' },
    { city: 'Tulsa', state: 'OK' },
    { city: 'Wichita', state: 'KS' },
    { city: 'Bakersfield', state: 'CA' },
    { city: 'Aurora', state: 'CO' },
    { city: 'Santa Ana', state: 'CA' },
    { city: 'St. Petersburg', state: 'FL' },
    { city: 'Stockton', state: 'CA' },
    { city: 'Madison', state: 'WI' },
    { city: 'Lubbock', state: 'TX' },
    { city: 'Chandler', state: 'AZ' },
    { city: 'Scottsdale', state: 'AZ' },
    { city: 'Reno', state: 'NV' },
    { city: 'Norfolk', state: 'VA' },
    { city: 'Durham', state: 'NC' },
    { city: 'Laredo', state: 'TX' },
    { city: 'Lubbock', state: 'TX' },
    { city: 'Garland', state: 'TX' },
    { city: 'Glendale', state: 'AZ' },
    { city: 'Hialeah', state: 'FL' },
    { city: 'Rochester', state: 'NY' },
    { city: 'Irving', state: 'TX' },
    { city: 'Fremont', state: 'CA' },
    { city: 'Richmond', state: 'VA' },
    { city: 'Boise', state: 'ID' },
    { city: 'Des Moines', state: 'IA' },
    { city: 'Modesto', state: 'CA' },
    { city: 'Birmingham', state: 'AL' },
    { city: 'Tacoma', state: 'WA' },
    { city: 'Fontana', state: 'CA' },
    { city: 'Oxnard', state: 'CA' },
    { city: 'Montgomery', state: 'AL' },
    { city: 'Moreno Valley', state: 'CA' },
    { city: 'Shreveport', state: 'LA' },
    { city: 'Akron', state: 'OH' },
    { city: 'Yonkers', state: 'NY' },
    { city: 'Columbus', state: 'GA' },
    { city: 'Cary', state: 'NC' },
    { city: 'Grand Rapids', state: 'MI' },
    { city: 'Newport News', state: 'VA' },
    { city: 'Huntington Beach', state: 'CA' },
    { city: 'Amarillo', state: 'TX' },
    { city: 'Mobile', state: 'AL' },
    { city: 'Little Rock', state: 'AR' },
    { city: 'Augusta', state: 'GA' },
    { city: 'Aurora', state: 'IL' },
    { city: 'Salt Lake City', state: 'UT' },
    { city: 'Huntsville', state: 'AL' },
    { city: 'Worcester', state: 'MA' },
    { city: 'Knoxville', state: 'TN' },
    { city: 'Providence', state: 'RI' },
    { city: 'Santa Clarita', state: 'CA' },
    { city: 'Garden Grove', state: 'CA' },
    { city: 'Oceanside', state: 'CA' },
    { city: 'Jackson', state: 'MS' },
    { city: 'Chattanooga', state: 'TN' },
    { city: 'Fort Lauderdale', state: 'FL' },
    { city: 'Rancho Cucamonga', state: 'CA' },
    { city: 'Port St. Lucie', state: 'FL' }
];

module.exports = cityStatePairs;